-- ============================================
-- SUYAVARAA Fish Trap Decoy Seed Data
-- ============================================
-- Seeds 20 realistic decoy profiles for the Fish Trap system

INSERT INTO decoy_profiles (name, age, gender, city, bio, profile_photo_url, characteristics)
VALUES 
('Priya Sharma', 26, 'female', 'Mumbai', 'Software engineer by day, food blogger by night. Love exploring new restaurants and trying exotic cuisines. Looking for someone who appreciates good conversation and adventure.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&q=60', '{"personality": "professional", "red_flag_triggers": ["money_mention", "rush_relationship"]}'),
('Arjun Patel', 29, 'male', 'Delhi', 'Entrepreneur building my dream startup. Love traveling, hiking, and deep conversations about life. Seeking a partner who shares my ambition and values.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&q=60', '{"personality": "ambitious", "red_flag_triggers": ["investment_opportunity", "business_venture"]}'),
('Sneha Gupta', 24, 'female', 'Bangalore', 'UX Designer with a passion for creating beautiful digital experiences. Coffee addict, book lover, and weekend hiker. Looking for someone genuine who values kindness.', 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=500&q=60', '{"personality": "creative", "red_flag_triggers": ["contact_exchange", "meet_immediately"]}'),
('Rohan Singh', 31, 'male', 'Chennai', 'Doctor working in emergency medicine. Long shifts but love helping people. Playing guitar or exploring local cafes is focus. Seeking someone compassionate.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&q=60', '{"personality": "caring", "red_flag_triggers": ["emergency_money", "family_emergency"]}'),
('Ananya Reddy', 27, 'female', 'Hyderabad', 'Marketing manager who loves planning events and bringing people together. Fitness enthusiast, yoga practitioner, and amateur photographer.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&q=60', '{"personality": "social", "red_flag_triggers": ["gift_sending", "expensive_gifts"]}'),
('Vikram Kumar', 28, 'male', 'Pune', 'Data scientist fascinated by AI and machine learning. Love solving complex problems and teaching others. Weekend cycling and swimming.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&q=60', '{"personality": "intellectual", "red_flag_triggers": ["crypto_investment", "tech_startup"]}'),
('Kavya Menon', 25, 'female', 'Kochi', 'Journalist covering social issues and human stories. Passionate about making a difference. Love reading, writing, and meaningful conversations.', 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=500&q=60', '{"personality": "activist", "red_flag_triggers": ["charity_scam", "donation_request"]}'),
('Aditya Joshi', 30, 'male', 'Ahmedabad', 'Architect designing sustainable buildings for the future. Love sustainable living, organic farming, and eco-friendly travel.', 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=500&q=60', '{"personality": "environmentalist", "red_flag_triggers": ["property_investment", "real_estate"]}'),
('Meera Iyer', 26, 'female', 'Chennai', 'Classical dancer and teacher. Expressing emotions through movement and music. Love traditional arts, spirituality, and connecting with like-minded souls.', 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=500&q=60', '{"personality": "artistic", "red_flag_triggers": ["spiritual_scam", "guru_disciple"]}'),
('Rahul Verma', 32, 'male', 'Jaipur', 'Hotel manager overseeing luxury properties. Love fine dining, wine tasting, and cultural experiences. Well-traveled and always planning the next adventure.', 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&q=60', '{"personality": "luxury", "red_flag_triggers": ["expensive_dates", "luxury_lifestyle"]}'),
('Divya Nair', 24, 'female', 'Trivandrum', 'Recent law graduate passionate about justice and equality. Love debating ideas, watching documentaries, and volunteering.', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&q=60', '{"personality": "intellectual", "red_flag_triggers": ["legal_trouble", "court_case"]}'),
('Karan Malhotra', 29, 'male', 'Gurgaon', 'Investment banker with a work-hard-play-hard mentality. Love fine whiskey, golf, and networking events. Successful and ambitious.', 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=500&q=60', '{"personality": "corporate", "red_flag_triggers": ["stock_tips", "investment_advice"]}'),
('Pooja Agarwal', 27, 'female', 'Kolkata', 'Chef specializing in Bengali cuisine. Love experimenting in the kitchen and hosting dinner parties. Food is my love language!', 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=500&q=60', '{"personality": "culinary", "red_flag_triggers": ["food_delivery", "restaurant_investment"]}'),
('Siddharth Rao', 31, 'male', 'Mysore', 'Professor of literature and poetry enthusiast. Love discussing books, writing, and philosophical conversations.', 'https://images.unsplash.com/photo-1519085184581-285090412435?w=500&q=60', '{"personality": "academic", "red_flag_triggers": ["book_scam", "rare_manuscript"]}'),
('Nisha Kapoor', 25, 'female', 'Lucknow', 'Fashion designer creating sustainable clothing. Love ethical fashion, art galleries, and cultural festivals.', 'https://images.unsplash.com/photo-1524502392764-12844883141f?w=500&q=60', '{"personality": "creative", "red_flag_triggers": ["fashion_business", "clothing_line"]}'),
('Amitabh Saxena', 33, 'male', 'Varanasi', 'Spiritual guide and meditation teacher. Help others find inner peace and purpose. Love yoga, Ayurveda, and connecting with the divine.', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&q=60', '{"personality": "spiritual", "red_flag_triggers": ["spiritual_retreat", "meditation_center"]}'),
('Riya Choudhury', 26, 'female', 'Guwahati', 'Wildlife photographer and conservationist. Travel the world capturing endangered species and raising awareness. Love nature, adventure.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=500&q=60', '{"personality": "adventurous", "red_flag_triggers": ["conservation_project", "wildlife_fund"]}'),
('Manish Tiwari', 30, 'male', 'Indore', 'Music producer and DJ. Create beats and mix tracks for underground artists. Love electronic music, festivals, and late-night studio sessions.', 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=500&q=60', '{"personality": "musical", "red_flag_triggers": ["music_production", "studio_equipment"]}'),
('Swati Deshmukh', 28, 'female', 'Nagpur', 'Social entrepreneur running a startup for rural education. Passionate about bridging the education gap. Love reading, mentoring.', 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=500&q=60', '{"personality": "philanthropic", "red_flag_triggers": ["education_startup", "rural_development"]}'),
('Rajesh Khanna', 34, 'male', 'Surat', 'Real estate developer building smart cities. Love innovation, technology, and creating sustainable communities. Successful businessman.', 'https://images.unsplash.com/photo-1519085184581-285090412435?w=500&q=60', '{"personality": "entrepreneur", "red_flag_triggers": ["real_estate_investment", "property_development"]}');
